"""returns promotions loyalty held carts

Revision ID: 4dadb34ff5c5
Revises: 2a4f5d6f3eb0
Create Date: 2026-10-03 19:52:47.041610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dadb34ff5c5'
down_revision: Union[str, Sequence[str], None] = '2a4f5d6f3eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('held_cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('voucher_code', sa.String(length=30), nullable=True),
    sa.Column('note', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_held_cart_customer_id_customer')),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name=op.f('fk_held_cart_store_id_store')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_held_cart_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_held_cart'))
    )
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_held_cart_store_id'), ['store_id'], unique=False)

    op.create_table('promotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('erp_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('buy_qty', sa.Integer(), nullable=False),
    sa.Column('get_qty', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('min_spend', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_promotion_product_id_product')),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name=op.f('fk_promotion_store_id_store')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion')),
    sa.UniqueConstraint('erp_id', name=op.f('uq_promotion_erp_id'))
    )
    op.create_table('stock_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('erp_transfer_number', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name=op.f('fk_stock_request_store_id_store')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_stock_request_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_request'))
    )
    with op.batch_alter_table('stock_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_request_store_id'), ['store_id'], unique=False)

    op.create_table('sale_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=6), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('erp_status', sa.String(length=10), nullable=False),
    sa.Column('erp_return_number', sa.String(length=30), nullable=True),
    sa.Column('erp_attempts', sa.Integer(), nullable=False),
    sa.Column('erp_error', sa.String(length=500), nullable=True),
    sa.Column('erp_last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('erp_sending_until', sa.DateTime(), nullable=True),
    sa.Column('erp_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cashier_id'], ['user_account.id'], name=op.f('fk_sale_return_cashier_id_user_account')),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], name=op.f('fk_sale_return_sale_id_sale')),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], name=op.f('fk_sale_return_shift_id_shift')),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name=op.f('fk_sale_return_store_id_store')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_return')),
    sa.UniqueConstraint('number', name=op.f('uq_sale_return_number')),
    sa.UniqueConstraint('public_id', name=op.f('uq_sale_return_public_id'))
    )
    with op.batch_alter_table('sale_return', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_return_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_return_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_return_erp_status'), ['erp_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_return_sale_id'), ['sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_return_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_return_store_id'), ['store_id'], unique=False)

    op.create_table('return_refund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.CheckConstraint('amount > 0', name=op.f('ck_return_refund_amount_positive')),
    sa.ForeignKeyConstraint(['return_id'], ['sale_return.id'], name=op.f('fk_return_refund_return_id_sale_return'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_refund'))
    )
    with op.batch_alter_table('return_refund', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_refund_return_id'), ['return_id'], unique=False)

    op.create_table('sale_return_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('sale_line_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('discount_pct', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Integer(), nullable=False),
    sa.CheckConstraint('qty > 0', name=op.f('ck_sale_return_line_qty_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_sale_return_line_product_id_product')),
    sa.ForeignKeyConstraint(['return_id'], ['sale_return.id'], name=op.f('fk_sale_return_line_return_id_sale_return'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_line_id'], ['sale_line.id'], name=op.f('fk_sale_return_line_sale_line_id_sale_line')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_return_line'))
    )
    with op.batch_alter_table('sale_return_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_return_line_return_id'), ['return_id'], unique=False)

    with op.batch_alter_table('cash_movement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by', sa.String(length=120), nullable=True))

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voucher_code', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('points_earned', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('points_redeemed', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('approved_by', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('offline', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('voided_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('sale_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promo', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_line', schema=None) as batch_op:
        batch_op.drop_column('promo')

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('voided_at')
        batch_op.drop_column('offline')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('points_redeemed')
        batch_op.drop_column('points_earned')
        batch_op.drop_column('voucher_code')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('points')

    with op.batch_alter_table('cash_movement', schema=None) as batch_op:
        batch_op.drop_column('approved_by')

    with op.batch_alter_table('sale_return_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_return_line_return_id'))

    op.drop_table('sale_return_line')
    with op.batch_alter_table('return_refund', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_refund_return_id'))

    op.drop_table('return_refund')
    with op.batch_alter_table('sale_return', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_return_store_id'))
        batch_op.drop_index(batch_op.f('ix_sale_return_shift_id'))
        batch_op.drop_index(batch_op.f('ix_sale_return_sale_id'))
        batch_op.drop_index(batch_op.f('ix_sale_return_erp_status'))
        batch_op.drop_index(batch_op.f('ix_sale_return_created_at'))
        batch_op.drop_index(batch_op.f('ix_sale_return_business_date'))

    op.drop_table('sale_return')
    with op.batch_alter_table('stock_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_request_store_id'))

    op.drop_table('stock_request')
    op.drop_table('promotion')
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_held_cart_store_id'))

    op.drop_table('held_cart')
    # ### end Alembic commands ###
