"""initial schema

Revision ID: 9b8d1f6747de
Revises: 
Create Date: 2026-10-03 14:51:04.181851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8d1f6747de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('erp_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('group_name', sa.String(length=80), nullable=True),
    sa.Column('discount_pct', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer')),
    sa.UniqueConstraint('erp_id', name=op.f('uq_customer_erp_id'))
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_name'), ['name'], unique=False)

    op.create_table('number_sequence',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_number_sequence'))
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('erp_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('barcode', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('brand', sa.String(length=60), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product')),
    sa.UniqueConstraint('erp_id', name=op.f('uq_product_erp_id'))
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_sku'), ['sku'], unique=False)

    op.create_table('setting',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_setting'))
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('erp_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store')),
    sa.UniqueConstraint('erp_id', name=op.f('uq_store_erp_id'))
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account')),
    sa.UniqueConstraint('username', name=op.f('uq_user_account_username'))
    )
    op.create_table('auth_session',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_auth_session_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_auth_session'))
    )
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_session_user_id'), ['user_id'], unique=False)

    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('opening_float', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('expected_cash', sa.Integer(), nullable=True),
    sa.Column('counted_cash', sa.Integer(), nullable=True),
    sa.Column('closing_note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['user_account.id'], name=op.f('fk_shift_closed_by_id_user_account')),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name=op.f('fk_shift_store_id_store')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_shift_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift')),
    sa.UniqueConstraint('number', name=op.f('uq_shift_number'))
    )
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_user_id'), ['user_id'], unique=False)

    op.create_table('stock_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_stock_level_product_id_product')),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name=op.f('fk_stock_level_store_id_store')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_level')),
    sa.UniqueConstraint('store_id', 'product_id', name='store_product')
    )
    with op.batch_alter_table('stock_level', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_level_store_id'), ['store_id'], unique=False)

    op.create_table('sync_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('trigger', sa.String(length=10), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_sync_run_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_run'))
    )
    with op.batch_alter_table('sync_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_run_started_at'), ['started_at'], unique=False)

    op.create_table('cash_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_cash_movement_amount_positive')),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], name=op.f('fk_cash_movement_shift_id_shift')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_cash_movement_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_movement'))
    )
    with op.batch_alter_table('cash_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_movement_shift_id'), ['shift_id'], unique=False)

    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tax_rate', sa.Integer(), nullable=False),
    sa.Column('gross', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('cash_tendered', sa.Integer(), nullable=False),
    sa.Column('change_due', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('erp_status', sa.String(length=10), nullable=False),
    sa.Column('erp_order_number', sa.String(length=30), nullable=True),
    sa.Column('erp_invoice_number', sa.String(length=30), nullable=True),
    sa.Column('erp_attempts', sa.Integer(), nullable=False),
    sa.Column('erp_error', sa.String(length=500), nullable=True),
    sa.Column('erp_last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('erp_sending_until', sa.DateTime(), nullable=True),
    sa.Column('erp_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cashier_id'], ['user_account.id'], name=op.f('fk_sale_cashier_id_user_account')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_sale_customer_id_customer')),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], name=op.f('fk_sale_shift_id_shift')),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name=op.f('fk_sale_store_id_store')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale')),
    sa.UniqueConstraint('number', name=op.f('uq_sale_number')),
    sa.UniqueConstraint('public_id', name=op.f('uq_sale_public_id'))
    )
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_erp_status'), ['erp_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_store_id'), ['store_id'], unique=False)

    op.create_table('sale_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('discount_pct', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Integer(), nullable=False),
    sa.CheckConstraint('discount_pct >= 0 AND discount_pct <= 100', name=op.f('ck_sale_line_discount_range')),
    sa.CheckConstraint('qty > 0', name=op.f('ck_sale_line_qty_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_sale_line_product_id_product')),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], name=op.f('fk_sale_line_sale_id_sale'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_line'))
    )
    with op.batch_alter_table('sale_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_line_sale_id'), ['sale_id'], unique=False)

    op.create_table('sale_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.CheckConstraint('amount > 0', name=op.f('ck_sale_payment_amount_positive')),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], name=op.f('fk_sale_payment_sale_id_sale'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_payment'))
    )
    with op.batch_alter_table('sale_payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_payment_sale_id'), ['sale_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_payment_sale_id'))

    op.drop_table('sale_payment')
    with op.batch_alter_table('sale_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_line_sale_id'))

    op.drop_table('sale_line')
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_store_id'))
        batch_op.drop_index(batch_op.f('ix_sale_shift_id'))
        batch_op.drop_index(batch_op.f('ix_sale_erp_status'))
        batch_op.drop_index(batch_op.f('ix_sale_created_at'))
        batch_op.drop_index(batch_op.f('ix_sale_business_date'))

    op.drop_table('sale')
    with op.batch_alter_table('cash_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_movement_shift_id'))

    op.drop_table('cash_movement')
    with op.batch_alter_table('sync_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_run_started_at'))

    op.drop_table('sync_run')
    with op.batch_alter_table('stock_level', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_level_store_id'))

    op.drop_table('stock_level')
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_user_id'))
        batch_op.drop_index(batch_op.f('ix_shift_status'))

    op.drop_table('shift')
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_session_user_id'))

    op.drop_table('auth_session')
    op.drop_table('user_account')
    op.drop_table('store')
    op.drop_table('setting')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_sku'))
        batch_op.drop_index(batch_op.f('ix_product_barcode'))

    op.drop_table('product')
    op.drop_table('number_sequence')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_name'))

    op.drop_table('customer')
    # ### end Alembic commands ###
