"""cashier pin preferences and device sessions

Revision ID: d99fa712bedd
Revises: 4dadb34ff5c5
Create Date: 2026-10-04 09:21:14.498817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99fa712bedd'
down_revision: Union[str, Sequence[str], None] = '4dadb34ff5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=200), nullable=True))

    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_hash', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('preferences', sa.JSON(), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_column('preferences')
        batch_op.drop_column('pin_hash')

    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.drop_column('user_agent')
        batch_op.drop_column('last_seen_at')

    # ### end Alembic commands ###
